/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RewardProgramsPageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RewardProgramsPageResponse{}

// RewardProgramsPageResponse struct for RewardProgramsPageResponse
type RewardProgramsPageResponse struct {
	// Number of resources returned.
	Count int32 `json:"count"`
	// An array of reward program objects.
	Data []RewardProgramsResponse `json:"data"`
	// Sort order index of the last resource in the returned array.
	EndIndex int64 `json:"end_index"`
	// A value of `true` indicates that more unreturned resources exist.
	IsMore *bool `json:"is_more,omitempty"`
	// Sort order index of the first resource in the returned array.
	StartIndex int64 `json:"start_index"`
}

type _RewardProgramsPageResponse RewardProgramsPageResponse

// NewRewardProgramsPageResponse instantiates a new RewardProgramsPageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRewardProgramsPageResponse(count int32, data []RewardProgramsResponse, endIndex int64, startIndex int64) *RewardProgramsPageResponse {
	this := RewardProgramsPageResponse{}
	this.Count = count
	this.Data = data
	this.EndIndex = endIndex
	this.StartIndex = startIndex
	return &this
}

// NewRewardProgramsPageResponseWithDefaults instantiates a new RewardProgramsPageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRewardProgramsPageResponseWithDefaults() *RewardProgramsPageResponse {
	this := RewardProgramsPageResponse{}
	return &this
}

// GetCount returns the Count field value
func (o *RewardProgramsPageResponse) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsPageResponse) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *RewardProgramsPageResponse) SetCount(v int32) {
	o.Count = v
}

// GetData returns the Data field value
func (o *RewardProgramsPageResponse) GetData() []RewardProgramsResponse {
	if o == nil {
		var ret []RewardProgramsResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsPageResponse) GetDataOk() ([]RewardProgramsResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *RewardProgramsPageResponse) SetData(v []RewardProgramsResponse) {
	o.Data = v
}

// GetEndIndex returns the EndIndex field value
func (o *RewardProgramsPageResponse) GetEndIndex() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndIndex
}

// GetEndIndexOk returns a tuple with the EndIndex field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsPageResponse) GetEndIndexOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndIndex, true
}

// SetEndIndex sets field value
func (o *RewardProgramsPageResponse) SetEndIndex(v int64) {
	o.EndIndex = v
}

// GetIsMore returns the IsMore field value if set, zero value otherwise.
func (o *RewardProgramsPageResponse) GetIsMore() bool {
	if o == nil || IsNil(o.IsMore) {
		var ret bool
		return ret
	}
	return *o.IsMore
}

// GetIsMoreOk returns a tuple with the IsMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RewardProgramsPageResponse) GetIsMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMore) {
		return nil, false
	}
	return o.IsMore, true
}

// HasIsMore returns a boolean if a field has been set.
func (o *RewardProgramsPageResponse) HasIsMore() bool {
	if o != nil && !IsNil(o.IsMore) {
		return true
	}

	return false
}

// SetIsMore gets a reference to the given bool and assigns it to the IsMore field.
func (o *RewardProgramsPageResponse) SetIsMore(v bool) {
	o.IsMore = &v
}

// GetStartIndex returns the StartIndex field value
func (o *RewardProgramsPageResponse) GetStartIndex() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartIndex
}

// GetStartIndexOk returns a tuple with the StartIndex field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsPageResponse) GetStartIndexOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartIndex, true
}

// SetStartIndex sets field value
func (o *RewardProgramsPageResponse) SetStartIndex(v int64) {
	o.StartIndex = v
}

func (o RewardProgramsPageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RewardProgramsPageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["data"] = o.Data
	toSerialize["end_index"] = o.EndIndex
	if !IsNil(o.IsMore) {
		toSerialize["is_more"] = o.IsMore
	}
	toSerialize["start_index"] = o.StartIndex
	return toSerialize, nil
}

func (o *RewardProgramsPageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"data",
		"end_index",
		"start_index",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRewardProgramsPageResponse := _RewardProgramsPageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRewardProgramsPageResponse)

	if err != nil {
		return err
	}

	*o = RewardProgramsPageResponse(varRewardProgramsPageResponse)

	return err
}

type NullableRewardProgramsPageResponse struct {
	value *RewardProgramsPageResponse
	isSet bool
}

func (v NullableRewardProgramsPageResponse) Get() *RewardProgramsPageResponse {
	return v.value
}

func (v *NullableRewardProgramsPageResponse) Set(val *RewardProgramsPageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRewardProgramsPageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRewardProgramsPageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRewardProgramsPageResponse(val *RewardProgramsPageResponse) *NullableRewardProgramsPageResponse {
	return &NullableRewardProgramsPageResponse{value: val, isSet: true}
}

func (v NullableRewardProgramsPageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRewardProgramsPageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


