/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DirectDepositRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectDepositRequest{}

// DirectDepositRequest struct for DirectDepositRequest
type DirectDepositRequest struct {
	AccountNumber string `json:"account_number"`
	Amount float32 `json:"amount"`
	CompanyDiscretionaryData *string `json:"company_discretionary_data,omitempty"`
	CompanyEntryDescription *string `json:"company_entry_description,omitempty"`
	CompanyIdentification *string `json:"company_identification,omitempty"`
	CompanyName *string `json:"company_name,omitempty"`
	EarlyPayEligible *bool `json:"earlyPayEligible,omitempty"`
	IndividualIdentificationNumber *string `json:"individual_identification_number,omitempty"`
	IndividualName *string `json:"individual_name,omitempty"`
	SettlementDate time.Time `json:"settlement_date"`
	StandardEntryClassCode *string `json:"standard_entry_class_code,omitempty"`
	Token *string `json:"token,omitempty"`
	Type string `json:"type"`
}

type _DirectDepositRequest DirectDepositRequest

// NewDirectDepositRequest instantiates a new DirectDepositRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectDepositRequest(accountNumber string, amount float32, settlementDate time.Time, type_ string) *DirectDepositRequest {
	this := DirectDepositRequest{}
	this.AccountNumber = accountNumber
	this.Amount = amount
	var earlyPayEligible bool = false
	this.EarlyPayEligible = &earlyPayEligible
	this.SettlementDate = settlementDate
	this.Type = type_
	return &this
}

// NewDirectDepositRequestWithDefaults instantiates a new DirectDepositRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectDepositRequestWithDefaults() *DirectDepositRequest {
	this := DirectDepositRequest{}
	var earlyPayEligible bool = false
	this.EarlyPayEligible = &earlyPayEligible
	return &this
}

// GetAccountNumber returns the AccountNumber field value
func (o *DirectDepositRequest) GetAccountNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetAccountNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountNumber, true
}

// SetAccountNumber sets field value
func (o *DirectDepositRequest) SetAccountNumber(v string) {
	o.AccountNumber = v
}

// GetAmount returns the Amount field value
func (o *DirectDepositRequest) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *DirectDepositRequest) SetAmount(v float32) {
	o.Amount = v
}

// GetCompanyDiscretionaryData returns the CompanyDiscretionaryData field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetCompanyDiscretionaryData() string {
	if o == nil || IsNil(o.CompanyDiscretionaryData) {
		var ret string
		return ret
	}
	return *o.CompanyDiscretionaryData
}

// GetCompanyDiscretionaryDataOk returns a tuple with the CompanyDiscretionaryData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetCompanyDiscretionaryDataOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyDiscretionaryData) {
		return nil, false
	}
	return o.CompanyDiscretionaryData, true
}

// HasCompanyDiscretionaryData returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasCompanyDiscretionaryData() bool {
	if o != nil && !IsNil(o.CompanyDiscretionaryData) {
		return true
	}

	return false
}

// SetCompanyDiscretionaryData gets a reference to the given string and assigns it to the CompanyDiscretionaryData field.
func (o *DirectDepositRequest) SetCompanyDiscretionaryData(v string) {
	o.CompanyDiscretionaryData = &v
}

// GetCompanyEntryDescription returns the CompanyEntryDescription field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetCompanyEntryDescription() string {
	if o == nil || IsNil(o.CompanyEntryDescription) {
		var ret string
		return ret
	}
	return *o.CompanyEntryDescription
}

// GetCompanyEntryDescriptionOk returns a tuple with the CompanyEntryDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetCompanyEntryDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyEntryDescription) {
		return nil, false
	}
	return o.CompanyEntryDescription, true
}

// HasCompanyEntryDescription returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasCompanyEntryDescription() bool {
	if o != nil && !IsNil(o.CompanyEntryDescription) {
		return true
	}

	return false
}

// SetCompanyEntryDescription gets a reference to the given string and assigns it to the CompanyEntryDescription field.
func (o *DirectDepositRequest) SetCompanyEntryDescription(v string) {
	o.CompanyEntryDescription = &v
}

// GetCompanyIdentification returns the CompanyIdentification field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetCompanyIdentification() string {
	if o == nil || IsNil(o.CompanyIdentification) {
		var ret string
		return ret
	}
	return *o.CompanyIdentification
}

// GetCompanyIdentificationOk returns a tuple with the CompanyIdentification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetCompanyIdentificationOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyIdentification) {
		return nil, false
	}
	return o.CompanyIdentification, true
}

// HasCompanyIdentification returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasCompanyIdentification() bool {
	if o != nil && !IsNil(o.CompanyIdentification) {
		return true
	}

	return false
}

// SetCompanyIdentification gets a reference to the given string and assigns it to the CompanyIdentification field.
func (o *DirectDepositRequest) SetCompanyIdentification(v string) {
	o.CompanyIdentification = &v
}

// GetCompanyName returns the CompanyName field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetCompanyName() string {
	if o == nil || IsNil(o.CompanyName) {
		var ret string
		return ret
	}
	return *o.CompanyName
}

// GetCompanyNameOk returns a tuple with the CompanyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetCompanyNameOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyName) {
		return nil, false
	}
	return o.CompanyName, true
}

// HasCompanyName returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasCompanyName() bool {
	if o != nil && !IsNil(o.CompanyName) {
		return true
	}

	return false
}

// SetCompanyName gets a reference to the given string and assigns it to the CompanyName field.
func (o *DirectDepositRequest) SetCompanyName(v string) {
	o.CompanyName = &v
}

// GetEarlyPayEligible returns the EarlyPayEligible field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetEarlyPayEligible() bool {
	if o == nil || IsNil(o.EarlyPayEligible) {
		var ret bool
		return ret
	}
	return *o.EarlyPayEligible
}

// GetEarlyPayEligibleOk returns a tuple with the EarlyPayEligible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetEarlyPayEligibleOk() (*bool, bool) {
	if o == nil || IsNil(o.EarlyPayEligible) {
		return nil, false
	}
	return o.EarlyPayEligible, true
}

// HasEarlyPayEligible returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasEarlyPayEligible() bool {
	if o != nil && !IsNil(o.EarlyPayEligible) {
		return true
	}

	return false
}

// SetEarlyPayEligible gets a reference to the given bool and assigns it to the EarlyPayEligible field.
func (o *DirectDepositRequest) SetEarlyPayEligible(v bool) {
	o.EarlyPayEligible = &v
}

// GetIndividualIdentificationNumber returns the IndividualIdentificationNumber field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetIndividualIdentificationNumber() string {
	if o == nil || IsNil(o.IndividualIdentificationNumber) {
		var ret string
		return ret
	}
	return *o.IndividualIdentificationNumber
}

// GetIndividualIdentificationNumberOk returns a tuple with the IndividualIdentificationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetIndividualIdentificationNumberOk() (*string, bool) {
	if o == nil || IsNil(o.IndividualIdentificationNumber) {
		return nil, false
	}
	return o.IndividualIdentificationNumber, true
}

// HasIndividualIdentificationNumber returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasIndividualIdentificationNumber() bool {
	if o != nil && !IsNil(o.IndividualIdentificationNumber) {
		return true
	}

	return false
}

// SetIndividualIdentificationNumber gets a reference to the given string and assigns it to the IndividualIdentificationNumber field.
func (o *DirectDepositRequest) SetIndividualIdentificationNumber(v string) {
	o.IndividualIdentificationNumber = &v
}

// GetIndividualName returns the IndividualName field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetIndividualName() string {
	if o == nil || IsNil(o.IndividualName) {
		var ret string
		return ret
	}
	return *o.IndividualName
}

// GetIndividualNameOk returns a tuple with the IndividualName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetIndividualNameOk() (*string, bool) {
	if o == nil || IsNil(o.IndividualName) {
		return nil, false
	}
	return o.IndividualName, true
}

// HasIndividualName returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasIndividualName() bool {
	if o != nil && !IsNil(o.IndividualName) {
		return true
	}

	return false
}

// SetIndividualName gets a reference to the given string and assigns it to the IndividualName field.
func (o *DirectDepositRequest) SetIndividualName(v string) {
	o.IndividualName = &v
}

// GetSettlementDate returns the SettlementDate field value
func (o *DirectDepositRequest) GetSettlementDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SettlementDate
}

// GetSettlementDateOk returns a tuple with the SettlementDate field value
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetSettlementDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SettlementDate, true
}

// SetSettlementDate sets field value
func (o *DirectDepositRequest) SetSettlementDate(v time.Time) {
	o.SettlementDate = v
}

// GetStandardEntryClassCode returns the StandardEntryClassCode field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetStandardEntryClassCode() string {
	if o == nil || IsNil(o.StandardEntryClassCode) {
		var ret string
		return ret
	}
	return *o.StandardEntryClassCode
}

// GetStandardEntryClassCodeOk returns a tuple with the StandardEntryClassCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetStandardEntryClassCodeOk() (*string, bool) {
	if o == nil || IsNil(o.StandardEntryClassCode) {
		return nil, false
	}
	return o.StandardEntryClassCode, true
}

// HasStandardEntryClassCode returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasStandardEntryClassCode() bool {
	if o != nil && !IsNil(o.StandardEntryClassCode) {
		return true
	}

	return false
}

// SetStandardEntryClassCode gets a reference to the given string and assigns it to the StandardEntryClassCode field.
func (o *DirectDepositRequest) SetStandardEntryClassCode(v string) {
	o.StandardEntryClassCode = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *DirectDepositRequest) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *DirectDepositRequest) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *DirectDepositRequest) SetToken(v string) {
	o.Token = &v
}

// GetType returns the Type field value
func (o *DirectDepositRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DirectDepositRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DirectDepositRequest) SetType(v string) {
	o.Type = v
}

func (o DirectDepositRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectDepositRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_number"] = o.AccountNumber
	toSerialize["amount"] = o.Amount
	if !IsNil(o.CompanyDiscretionaryData) {
		toSerialize["company_discretionary_data"] = o.CompanyDiscretionaryData
	}
	if !IsNil(o.CompanyEntryDescription) {
		toSerialize["company_entry_description"] = o.CompanyEntryDescription
	}
	if !IsNil(o.CompanyIdentification) {
		toSerialize["company_identification"] = o.CompanyIdentification
	}
	if !IsNil(o.CompanyName) {
		toSerialize["company_name"] = o.CompanyName
	}
	if !IsNil(o.EarlyPayEligible) {
		toSerialize["earlyPayEligible"] = o.EarlyPayEligible
	}
	if !IsNil(o.IndividualIdentificationNumber) {
		toSerialize["individual_identification_number"] = o.IndividualIdentificationNumber
	}
	if !IsNil(o.IndividualName) {
		toSerialize["individual_name"] = o.IndividualName
	}
	toSerialize["settlement_date"] = o.SettlementDate
	if !IsNil(o.StandardEntryClassCode) {
		toSerialize["standard_entry_class_code"] = o.StandardEntryClassCode
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *DirectDepositRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_number",
		"amount",
		"settlement_date",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectDepositRequest := _DirectDepositRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectDepositRequest)

	if err != nil {
		return err
	}

	*o = DirectDepositRequest(varDirectDepositRequest)

	return err
}

type NullableDirectDepositRequest struct {
	value *DirectDepositRequest
	isSet bool
}

func (v NullableDirectDepositRequest) Get() *DirectDepositRequest {
	return v.value
}

func (v *NullableDirectDepositRequest) Set(val *DirectDepositRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectDepositRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectDepositRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectDepositRequest(val *DirectDepositRequest) *NullableDirectDepositRequest {
	return &NullableDirectDepositRequest{value: val, isSet: true}
}

func (v NullableDirectDepositRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectDepositRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


