/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RewardProgramsEntriesPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RewardProgramsEntriesPage{}

// RewardProgramsEntriesPage Return paginated reward entries.
type RewardProgramsEntriesPage struct {
	// Number of resources returned.
	Count int32 `json:"count"`
	// An array of reward entry objects.
	Data []RewardProgramsEntriesResponse `json:"data"`
	// Sort order index of the last resource in the returned array.
	EndIndex int64 `json:"end_index"`
	// A value of `true` indicates that more unreturned resources exist.
	IsMore bool `json:"is_more"`
	// Sort order index of the first resource in the returned array.
	StartIndex int64 `json:"start_index"`
}

type _RewardProgramsEntriesPage RewardProgramsEntriesPage

// NewRewardProgramsEntriesPage instantiates a new RewardProgramsEntriesPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRewardProgramsEntriesPage(count int32, data []RewardProgramsEntriesResponse, endIndex int64, isMore bool, startIndex int64) *RewardProgramsEntriesPage {
	this := RewardProgramsEntriesPage{}
	this.Count = count
	this.Data = data
	this.EndIndex = endIndex
	this.IsMore = isMore
	this.StartIndex = startIndex
	return &this
}

// NewRewardProgramsEntriesPageWithDefaults instantiates a new RewardProgramsEntriesPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRewardProgramsEntriesPageWithDefaults() *RewardProgramsEntriesPage {
	this := RewardProgramsEntriesPage{}
	return &this
}

// GetCount returns the Count field value
func (o *RewardProgramsEntriesPage) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsEntriesPage) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *RewardProgramsEntriesPage) SetCount(v int32) {
	o.Count = v
}

// GetData returns the Data field value
func (o *RewardProgramsEntriesPage) GetData() []RewardProgramsEntriesResponse {
	if o == nil {
		var ret []RewardProgramsEntriesResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsEntriesPage) GetDataOk() ([]RewardProgramsEntriesResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *RewardProgramsEntriesPage) SetData(v []RewardProgramsEntriesResponse) {
	o.Data = v
}

// GetEndIndex returns the EndIndex field value
func (o *RewardProgramsEntriesPage) GetEndIndex() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndIndex
}

// GetEndIndexOk returns a tuple with the EndIndex field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsEntriesPage) GetEndIndexOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndIndex, true
}

// SetEndIndex sets field value
func (o *RewardProgramsEntriesPage) SetEndIndex(v int64) {
	o.EndIndex = v
}

// GetIsMore returns the IsMore field value
func (o *RewardProgramsEntriesPage) GetIsMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsMore
}

// GetIsMoreOk returns a tuple with the IsMore field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsEntriesPage) GetIsMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsMore, true
}

// SetIsMore sets field value
func (o *RewardProgramsEntriesPage) SetIsMore(v bool) {
	o.IsMore = v
}

// GetStartIndex returns the StartIndex field value
func (o *RewardProgramsEntriesPage) GetStartIndex() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartIndex
}

// GetStartIndexOk returns a tuple with the StartIndex field value
// and a boolean to check if the value has been set.
func (o *RewardProgramsEntriesPage) GetStartIndexOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartIndex, true
}

// SetStartIndex sets field value
func (o *RewardProgramsEntriesPage) SetStartIndex(v int64) {
	o.StartIndex = v
}

func (o RewardProgramsEntriesPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RewardProgramsEntriesPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["data"] = o.Data
	toSerialize["end_index"] = o.EndIndex
	toSerialize["is_more"] = o.IsMore
	toSerialize["start_index"] = o.StartIndex
	return toSerialize, nil
}

func (o *RewardProgramsEntriesPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"data",
		"end_index",
		"is_more",
		"start_index",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRewardProgramsEntriesPage := _RewardProgramsEntriesPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRewardProgramsEntriesPage)

	if err != nil {
		return err
	}

	*o = RewardProgramsEntriesPage(varRewardProgramsEntriesPage)

	return err
}

type NullableRewardProgramsEntriesPage struct {
	value *RewardProgramsEntriesPage
	isSet bool
}

func (v NullableRewardProgramsEntriesPage) Get() *RewardProgramsEntriesPage {
	return v.value
}

func (v *NullableRewardProgramsEntriesPage) Set(val *RewardProgramsEntriesPage) {
	v.value = val
	v.isSet = true
}

func (v NullableRewardProgramsEntriesPage) IsSet() bool {
	return v.isSet
}

func (v *NullableRewardProgramsEntriesPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRewardProgramsEntriesPage(val *RewardProgramsEntriesPage) *NullableRewardProgramsEntriesPage {
	return &NullableRewardProgramsEntriesPage{value: val, isSet: true}
}

func (v NullableRewardProgramsEntriesPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRewardProgramsEntriesPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


