/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CommandoModeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommandoModeRequest{}

// CommandoModeRequest struct for CommandoModeRequest
type CommandoModeRequest struct {
	CommandoModeEnables *CommandoModeEnables `json:"commando_mode_enables,omitempty"`
	// Unique identifier of the associated program gateway funding source.
	ProgramGatewayFundingSourceToken *string `json:"program_gateway_funding_source_token,omitempty"`
	RealTimeStandinCriteria *RealTimeStandinCriteria `json:"real_time_standin_criteria,omitempty"`
	// Unique identifier of the Commando Mode control set.
	Token *string `json:"token,omitempty"`
}

// NewCommandoModeRequest instantiates a new CommandoModeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommandoModeRequest() *CommandoModeRequest {
	this := CommandoModeRequest{}
	return &this
}

// NewCommandoModeRequestWithDefaults instantiates a new CommandoModeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommandoModeRequestWithDefaults() *CommandoModeRequest {
	this := CommandoModeRequest{}
	return &this
}

// GetCommandoModeEnables returns the CommandoModeEnables field value if set, zero value otherwise.
func (o *CommandoModeRequest) GetCommandoModeEnables() CommandoModeEnables {
	if o == nil || IsNil(o.CommandoModeEnables) {
		var ret CommandoModeEnables
		return ret
	}
	return *o.CommandoModeEnables
}

// GetCommandoModeEnablesOk returns a tuple with the CommandoModeEnables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommandoModeRequest) GetCommandoModeEnablesOk() (*CommandoModeEnables, bool) {
	if o == nil || IsNil(o.CommandoModeEnables) {
		return nil, false
	}
	return o.CommandoModeEnables, true
}

// HasCommandoModeEnables returns a boolean if a field has been set.
func (o *CommandoModeRequest) HasCommandoModeEnables() bool {
	if o != nil && !IsNil(o.CommandoModeEnables) {
		return true
	}

	return false
}

// SetCommandoModeEnables gets a reference to the given CommandoModeEnables and assigns it to the CommandoModeEnables field.
func (o *CommandoModeRequest) SetCommandoModeEnables(v CommandoModeEnables) {
	o.CommandoModeEnables = &v
}

// GetProgramGatewayFundingSourceToken returns the ProgramGatewayFundingSourceToken field value if set, zero value otherwise.
func (o *CommandoModeRequest) GetProgramGatewayFundingSourceToken() string {
	if o == nil || IsNil(o.ProgramGatewayFundingSourceToken) {
		var ret string
		return ret
	}
	return *o.ProgramGatewayFundingSourceToken
}

// GetProgramGatewayFundingSourceTokenOk returns a tuple with the ProgramGatewayFundingSourceToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommandoModeRequest) GetProgramGatewayFundingSourceTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ProgramGatewayFundingSourceToken) {
		return nil, false
	}
	return o.ProgramGatewayFundingSourceToken, true
}

// HasProgramGatewayFundingSourceToken returns a boolean if a field has been set.
func (o *CommandoModeRequest) HasProgramGatewayFundingSourceToken() bool {
	if o != nil && !IsNil(o.ProgramGatewayFundingSourceToken) {
		return true
	}

	return false
}

// SetProgramGatewayFundingSourceToken gets a reference to the given string and assigns it to the ProgramGatewayFundingSourceToken field.
func (o *CommandoModeRequest) SetProgramGatewayFundingSourceToken(v string) {
	o.ProgramGatewayFundingSourceToken = &v
}

// GetRealTimeStandinCriteria returns the RealTimeStandinCriteria field value if set, zero value otherwise.
func (o *CommandoModeRequest) GetRealTimeStandinCriteria() RealTimeStandinCriteria {
	if o == nil || IsNil(o.RealTimeStandinCriteria) {
		var ret RealTimeStandinCriteria
		return ret
	}
	return *o.RealTimeStandinCriteria
}

// GetRealTimeStandinCriteriaOk returns a tuple with the RealTimeStandinCriteria field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommandoModeRequest) GetRealTimeStandinCriteriaOk() (*RealTimeStandinCriteria, bool) {
	if o == nil || IsNil(o.RealTimeStandinCriteria) {
		return nil, false
	}
	return o.RealTimeStandinCriteria, true
}

// HasRealTimeStandinCriteria returns a boolean if a field has been set.
func (o *CommandoModeRequest) HasRealTimeStandinCriteria() bool {
	if o != nil && !IsNil(o.RealTimeStandinCriteria) {
		return true
	}

	return false
}

// SetRealTimeStandinCriteria gets a reference to the given RealTimeStandinCriteria and assigns it to the RealTimeStandinCriteria field.
func (o *CommandoModeRequest) SetRealTimeStandinCriteria(v RealTimeStandinCriteria) {
	o.RealTimeStandinCriteria = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *CommandoModeRequest) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommandoModeRequest) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *CommandoModeRequest) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *CommandoModeRequest) SetToken(v string) {
	o.Token = &v
}

func (o CommandoModeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommandoModeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CommandoModeEnables) {
		toSerialize["commando_mode_enables"] = o.CommandoModeEnables
	}
	if !IsNil(o.ProgramGatewayFundingSourceToken) {
		toSerialize["program_gateway_funding_source_token"] = o.ProgramGatewayFundingSourceToken
	}
	if !IsNil(o.RealTimeStandinCriteria) {
		toSerialize["real_time_standin_criteria"] = o.RealTimeStandinCriteria
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableCommandoModeRequest struct {
	value *CommandoModeRequest
	isSet bool
}

func (v NullableCommandoModeRequest) Get() *CommandoModeRequest {
	return v.value
}

func (v *NullableCommandoModeRequest) Set(val *CommandoModeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommandoModeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommandoModeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommandoModeRequest(val *CommandoModeRequest) *NullableCommandoModeRequest {
	return &NullableCommandoModeRequest{value: val, isSet: true}
}

func (v NullableCommandoModeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommandoModeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

