/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookRequestModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookRequestModel{}

// WebhookRequestModel struct for WebhookRequestModel
type WebhookRequestModel struct {
	// Indicates whether the webhook is active.
	Active *bool `json:"active,omitempty"`
	Config WebhookConfigModel `json:"config"`
	// Specifies the types of events for which notifications are sent.  The wildcard character `\\*` indicates that you receive all webhook notifications, or all notifications of a specified category. For example, `*` indicates that you receive all webhook notifications; `transaction.*` indicates that you receive all `transaction` webhook notifications.  *NOTE:* You can only use the wildcard character with the _base_ type events, not subcategories. For example, you cannot subscribe to `cardtransition.fulfillment.\\*` events, but you can subscribe to `cardtransition.*`.
	Events []string `json:"events"`
	// Descriptive name of the webhook.
	Name string `json:"name"`
	// Unique identifier of the webhook.
	Token *string `json:"token,omitempty"`
}

type _WebhookRequestModel WebhookRequestModel

// NewWebhookRequestModel instantiates a new WebhookRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookRequestModel(config WebhookConfigModel, events []string, name string) *WebhookRequestModel {
	this := WebhookRequestModel{}
	var active bool = true
	this.Active = &active
	this.Config = config
	this.Events = events
	this.Name = name
	return &this
}

// NewWebhookRequestModelWithDefaults instantiates a new WebhookRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookRequestModelWithDefaults() *WebhookRequestModel {
	this := WebhookRequestModel{}
	var active bool = true
	this.Active = &active
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *WebhookRequestModel) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRequestModel) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *WebhookRequestModel) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *WebhookRequestModel) SetActive(v bool) {
	o.Active = &v
}

// GetConfig returns the Config field value
func (o *WebhookRequestModel) GetConfig() WebhookConfigModel {
	if o == nil {
		var ret WebhookConfigModel
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *WebhookRequestModel) GetConfigOk() (*WebhookConfigModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Config, true
}

// SetConfig sets field value
func (o *WebhookRequestModel) SetConfig(v WebhookConfigModel) {
	o.Config = v
}

// GetEvents returns the Events field value
func (o *WebhookRequestModel) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *WebhookRequestModel) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *WebhookRequestModel) SetEvents(v []string) {
	o.Events = v
}

// GetName returns the Name field value
func (o *WebhookRequestModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebhookRequestModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebhookRequestModel) SetName(v string) {
	o.Name = v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *WebhookRequestModel) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRequestModel) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *WebhookRequestModel) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *WebhookRequestModel) SetToken(v string) {
	o.Token = &v
}

func (o WebhookRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookRequestModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	toSerialize["config"] = o.Config
	toSerialize["events"] = o.Events
	toSerialize["name"] = o.Name
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

func (o *WebhookRequestModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"config",
		"events",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookRequestModel := _WebhookRequestModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookRequestModel)

	if err != nil {
		return err
	}

	*o = WebhookRequestModel(varWebhookRequestModel)

	return err
}

type NullableWebhookRequestModel struct {
	value *WebhookRequestModel
	isSet bool
}

func (v NullableWebhookRequestModel) Get() *WebhookRequestModel {
	return v.value
}

func (v *NullableWebhookRequestModel) Set(val *WebhookRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookRequestModel(val *WebhookRequestModel) *NullableWebhookRequestModel {
	return &NullableWebhookRequestModel{value: val, isSet: true}
}

func (v NullableWebhookRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


