/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ProgramFundingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgramFundingResponse{}

// ProgramFundingResponse Returns details of a program funding entry.
type ProgramFundingResponse struct {
	// Amount of the funding.
	Amount decimal.Decimal `json:"amount"`
	// Timestamp when the funding entry was created.
	CreatedTime time.Time `json:"created_time"`
	CurrencyCode CurrencyCode `json:"currency_code"`
	// Additional notes for the funding entry.
	Memo string `json:"memo"`
	// Timestamp when the funding entry was posted.
	PostTime time.Time `json:"post_time"`
	// Unique identifier of the program.
	ShortCode string `json:"short_code"`
	// Unique identifier of the funding entry.
	Token string `json:"token"`
	// Timestamp when the funding entry was last updated.
	UpdatedTime time.Time `json:"updated_time"`
}

type _ProgramFundingResponse ProgramFundingResponse

// NewProgramFundingResponse instantiates a new ProgramFundingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramFundingResponse(amount decimal.Decimal, createdTime time.Time, currencyCode CurrencyCode, memo string, postTime time.Time, shortCode string, token string, updatedTime time.Time) *ProgramFundingResponse {
	this := ProgramFundingResponse{}
	this.Amount = amount
	this.CreatedTime = createdTime
	this.CurrencyCode = currencyCode
	this.Memo = memo
	this.PostTime = postTime
	this.ShortCode = shortCode
	this.Token = token
	this.UpdatedTime = updatedTime
	return &this
}

// NewProgramFundingResponseWithDefaults instantiates a new ProgramFundingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramFundingResponseWithDefaults() *ProgramFundingResponse {
	this := ProgramFundingResponse{}
	var currencyCode CurrencyCode = CURRENCYCODE_USD
	this.CurrencyCode = currencyCode
	return &this
}

// GetAmount returns the Amount field value
func (o *ProgramFundingResponse) GetAmount() decimal.Decimal {
	if o == nil {
		var ret decimal.Decimal
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetAmountOk() (*decimal.Decimal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ProgramFundingResponse) SetAmount(v decimal.Decimal) {
	o.Amount = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *ProgramFundingResponse) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *ProgramFundingResponse) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetCurrencyCode returns the CurrencyCode field value
func (o *ProgramFundingResponse) GetCurrencyCode() CurrencyCode {
	if o == nil {
		var ret CurrencyCode
		return ret
	}

	return o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetCurrencyCodeOk() (*CurrencyCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyCode, true
}

// SetCurrencyCode sets field value
func (o *ProgramFundingResponse) SetCurrencyCode(v CurrencyCode) {
	o.CurrencyCode = v
}

// GetMemo returns the Memo field value
func (o *ProgramFundingResponse) GetMemo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Memo
}

// GetMemoOk returns a tuple with the Memo field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetMemoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memo, true
}

// SetMemo sets field value
func (o *ProgramFundingResponse) SetMemo(v string) {
	o.Memo = v
}

// GetPostTime returns the PostTime field value
func (o *ProgramFundingResponse) GetPostTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.PostTime
}

// GetPostTimeOk returns a tuple with the PostTime field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetPostTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostTime, true
}

// SetPostTime sets field value
func (o *ProgramFundingResponse) SetPostTime(v time.Time) {
	o.PostTime = v
}

// GetShortCode returns the ShortCode field value
func (o *ProgramFundingResponse) GetShortCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShortCode
}

// GetShortCodeOk returns a tuple with the ShortCode field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetShortCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShortCode, true
}

// SetShortCode sets field value
func (o *ProgramFundingResponse) SetShortCode(v string) {
	o.ShortCode = v
}

// GetToken returns the Token field value
func (o *ProgramFundingResponse) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *ProgramFundingResponse) SetToken(v string) {
	o.Token = v
}

// GetUpdatedTime returns the UpdatedTime field value
func (o *ProgramFundingResponse) GetUpdatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedTime
}

// GetUpdatedTimeOk returns a tuple with the UpdatedTime field value
// and a boolean to check if the value has been set.
func (o *ProgramFundingResponse) GetUpdatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedTime, true
}

// SetUpdatedTime sets field value
func (o *ProgramFundingResponse) SetUpdatedTime(v time.Time) {
	o.UpdatedTime = v
}

func (o ProgramFundingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgramFundingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["currency_code"] = o.CurrencyCode
	toSerialize["memo"] = o.Memo
	toSerialize["post_time"] = o.PostTime
	toSerialize["short_code"] = o.ShortCode
	toSerialize["token"] = o.Token
	toSerialize["updated_time"] = o.UpdatedTime
	return toSerialize, nil
}

func (o *ProgramFundingResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"created_time",
		"currency_code",
		"memo",
		"post_time",
		"short_code",
		"token",
		"updated_time",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProgramFundingResponse := _ProgramFundingResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProgramFundingResponse)

	if err != nil {
		return err
	}

	*o = ProgramFundingResponse(varProgramFundingResponse)

	return err
}

type NullableProgramFundingResponse struct {
	value *ProgramFundingResponse
	isSet bool
}

func (v NullableProgramFundingResponse) Get() *ProgramFundingResponse {
	return v.value
}

func (v *NullableProgramFundingResponse) Set(val *ProgramFundingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramFundingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramFundingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramFundingResponse(val *ProgramFundingResponse) *NullableProgramFundingResponse {
	return &NullableProgramFundingResponse{value: val, isSet: true}
}

func (v NullableProgramFundingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramFundingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


