/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SubstatusEventResponseDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubstatusEventResponseDetails{}

// SubstatusEventResponseDetails Details of an event related to a substatus.
type SubstatusEventResponseDetails struct {
	// The channel through which the event occurred.
	Channel string `json:"channel"`
	// Creation time of the event.
	CreatedTime time.Time `json:"created_time"`
	// Effective date of the event, in UTC.
	EffectiveDate time.Time `json:"effective_date"`
	// Reason for the event.
	Reason *string `json:"reason,omitempty"`
	// The state of the event
	State string `json:"state"`
}

type _SubstatusEventResponseDetails SubstatusEventResponseDetails

// NewSubstatusEventResponseDetails instantiates a new SubstatusEventResponseDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubstatusEventResponseDetails(channel string, createdTime time.Time, effectiveDate time.Time, state string) *SubstatusEventResponseDetails {
	this := SubstatusEventResponseDetails{}
	this.Channel = channel
	this.CreatedTime = createdTime
	this.EffectiveDate = effectiveDate
	this.State = state
	return &this
}

// NewSubstatusEventResponseDetailsWithDefaults instantiates a new SubstatusEventResponseDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubstatusEventResponseDetailsWithDefaults() *SubstatusEventResponseDetails {
	this := SubstatusEventResponseDetails{}
	return &this
}

// GetChannel returns the Channel field value
func (o *SubstatusEventResponseDetails) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *SubstatusEventResponseDetails) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *SubstatusEventResponseDetails) SetChannel(v string) {
	o.Channel = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *SubstatusEventResponseDetails) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *SubstatusEventResponseDetails) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *SubstatusEventResponseDetails) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetEffectiveDate returns the EffectiveDate field value
func (o *SubstatusEventResponseDetails) GetEffectiveDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EffectiveDate
}

// GetEffectiveDateOk returns a tuple with the EffectiveDate field value
// and a boolean to check if the value has been set.
func (o *SubstatusEventResponseDetails) GetEffectiveDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveDate, true
}

// SetEffectiveDate sets field value
func (o *SubstatusEventResponseDetails) SetEffectiveDate(v time.Time) {
	o.EffectiveDate = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *SubstatusEventResponseDetails) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubstatusEventResponseDetails) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *SubstatusEventResponseDetails) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *SubstatusEventResponseDetails) SetReason(v string) {
	o.Reason = &v
}

// GetState returns the State field value
func (o *SubstatusEventResponseDetails) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *SubstatusEventResponseDetails) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *SubstatusEventResponseDetails) SetState(v string) {
	o.State = v
}

func (o SubstatusEventResponseDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubstatusEventResponseDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channel"] = o.Channel
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["effective_date"] = o.EffectiveDate
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *SubstatusEventResponseDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channel",
		"created_time",
		"effective_date",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubstatusEventResponseDetails := _SubstatusEventResponseDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubstatusEventResponseDetails)

	if err != nil {
		return err
	}

	*o = SubstatusEventResponseDetails(varSubstatusEventResponseDetails)

	return err
}

type NullableSubstatusEventResponseDetails struct {
	value *SubstatusEventResponseDetails
	isSet bool
}

func (v NullableSubstatusEventResponseDetails) Get() *SubstatusEventResponseDetails {
	return v.value
}

func (v *NullableSubstatusEventResponseDetails) Set(val *SubstatusEventResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableSubstatusEventResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableSubstatusEventResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubstatusEventResponseDetails(val *SubstatusEventResponseDetails) *NullableSubstatusEventResponseDetails {
	return &NullableSubstatusEventResponseDetails{value: val, isSet: true}
}

func (v NullableSubstatusEventResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubstatusEventResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


