/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DelinquencyStatus Delinquency status of an account.
type DelinquencyStatus string

// List of DelinquencyStatus
const (
	DELINQUENCYSTATUS_CURRENT DelinquencyStatus = "CURRENT"
	DELINQUENCYSTATUS_DELINQUENT DelinquencyStatus = "DELINQUENT"
)

// All allowed values of DelinquencyStatus enum
var AllowedDelinquencyStatusEnumValues = []DelinquencyStatus{
	"CURRENT",
	"DELINQUENT",
}

func (v *DelinquencyStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DelinquencyStatus(value)
	for _, existing := range AllowedDelinquencyStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DelinquencyStatus", value)
}

// NewDelinquencyStatusFromValue returns a pointer to a valid DelinquencyStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDelinquencyStatusFromValue(v string) (*DelinquencyStatus, error) {
	ev := DelinquencyStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DelinquencyStatus: valid values are %v", v, AllowedDelinquencyStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DelinquencyStatus) IsValid() bool {
	for _, existing := range AllowedDelinquencyStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DelinquencyStatus value
func (v DelinquencyStatus) Ptr() *DelinquencyStatus {
	return &v
}

type NullableDelinquencyStatus struct {
	value *DelinquencyStatus
	isSet bool
}

func (v NullableDelinquencyStatus) Get() *DelinquencyStatus {
	return v.value
}

func (v *NullableDelinquencyStatus) Set(val *DelinquencyStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDelinquencyStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDelinquencyStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelinquencyStatus(val *DelinquencyStatus) *NullableDelinquencyStatus {
	return &NullableDelinquencyStatus{value: val, isSet: true}
}

func (v NullableDelinquencyStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelinquencyStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

