/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AutoReloadModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoReloadModel{}

// AutoReloadModel Contains information about an auto reload. See <</core-api/auto-reload, Auto Reloads>> for more information.  Returned if an auto reload was executed.
type AutoReloadModel struct {
	// Specifies whether the auto reload is active.  Only one auto reload per level, per object, can be active.
	Active *bool `json:"active,omitempty"`
	Association *AutoReloadAssociation `json:"association,omitempty"`
	// Three-digit link:https://www.iso.org/iso-4217-currency-codes.html[ISO 4217 currency code, window=\"_blank\"].
	CurrencyCode string `json:"currency_code"`
	// Unique identifier of the funding source address to use for this auto reload.  If your funding source is an ACH account, then a `funding_source_address_token` is not required. If your funding source is a payment card, you must have at least one funding source address in order to create a GPA order.  Send a `GET` request to `/fundingsources/addresses/user/{user_token}` to retrieve address tokens for a user.  Send a `GET` request to `/fundingsources/addresses/business/{business_token}` to retrieve address tokens for a business.
	FundingSourceAddressToken *string `json:"funding_source_address_token,omitempty"`
	// Unique identifier of the funding source to use for this auto reload.  Send a `GET` request to `/fundingsources/user/{user_token}` to retrieve funding source tokens for a user.  Send a `GET` request to `/fundingsources/business/{business_token}` to retrieve funding source tokens for a business.
	FundingSourceToken *string `json:"funding_source_token,omitempty"`
	OrderScope OrderScope `json:"order_scope"`
	// Unique identifier of the auto reload.  If you do not include a token, the system will generate one automatically. This token is necessary for use in other API calls, so we recommend that rather than let the system generate one, you use a simple string that is easy to remember. This value cannot be updated.
	Token *string `json:"token,omitempty"`
}

type _AutoReloadModel AutoReloadModel

// NewAutoReloadModel instantiates a new AutoReloadModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoReloadModel(currencyCode string, orderScope OrderScope) *AutoReloadModel {
	this := AutoReloadModel{}
	var active bool = true
	this.Active = &active
	this.CurrencyCode = currencyCode
	this.OrderScope = orderScope
	return &this
}

// NewAutoReloadModelWithDefaults instantiates a new AutoReloadModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoReloadModelWithDefaults() *AutoReloadModel {
	this := AutoReloadModel{}
	var active bool = true
	this.Active = &active
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *AutoReloadModel) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoReloadModel) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *AutoReloadModel) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *AutoReloadModel) SetActive(v bool) {
	o.Active = &v
}

// GetAssociation returns the Association field value if set, zero value otherwise.
func (o *AutoReloadModel) GetAssociation() AutoReloadAssociation {
	if o == nil || IsNil(o.Association) {
		var ret AutoReloadAssociation
		return ret
	}
	return *o.Association
}

// GetAssociationOk returns a tuple with the Association field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoReloadModel) GetAssociationOk() (*AutoReloadAssociation, bool) {
	if o == nil || IsNil(o.Association) {
		return nil, false
	}
	return o.Association, true
}

// HasAssociation returns a boolean if a field has been set.
func (o *AutoReloadModel) HasAssociation() bool {
	if o != nil && !IsNil(o.Association) {
		return true
	}

	return false
}

// SetAssociation gets a reference to the given AutoReloadAssociation and assigns it to the Association field.
func (o *AutoReloadModel) SetAssociation(v AutoReloadAssociation) {
	o.Association = &v
}

// GetCurrencyCode returns the CurrencyCode field value
func (o *AutoReloadModel) GetCurrencyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value
// and a boolean to check if the value has been set.
func (o *AutoReloadModel) GetCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyCode, true
}

// SetCurrencyCode sets field value
func (o *AutoReloadModel) SetCurrencyCode(v string) {
	o.CurrencyCode = v
}

// GetFundingSourceAddressToken returns the FundingSourceAddressToken field value if set, zero value otherwise.
func (o *AutoReloadModel) GetFundingSourceAddressToken() string {
	if o == nil || IsNil(o.FundingSourceAddressToken) {
		var ret string
		return ret
	}
	return *o.FundingSourceAddressToken
}

// GetFundingSourceAddressTokenOk returns a tuple with the FundingSourceAddressToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoReloadModel) GetFundingSourceAddressTokenOk() (*string, bool) {
	if o == nil || IsNil(o.FundingSourceAddressToken) {
		return nil, false
	}
	return o.FundingSourceAddressToken, true
}

// HasFundingSourceAddressToken returns a boolean if a field has been set.
func (o *AutoReloadModel) HasFundingSourceAddressToken() bool {
	if o != nil && !IsNil(o.FundingSourceAddressToken) {
		return true
	}

	return false
}

// SetFundingSourceAddressToken gets a reference to the given string and assigns it to the FundingSourceAddressToken field.
func (o *AutoReloadModel) SetFundingSourceAddressToken(v string) {
	o.FundingSourceAddressToken = &v
}

// GetFundingSourceToken returns the FundingSourceToken field value if set, zero value otherwise.
func (o *AutoReloadModel) GetFundingSourceToken() string {
	if o == nil || IsNil(o.FundingSourceToken) {
		var ret string
		return ret
	}
	return *o.FundingSourceToken
}

// GetFundingSourceTokenOk returns a tuple with the FundingSourceToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoReloadModel) GetFundingSourceTokenOk() (*string, bool) {
	if o == nil || IsNil(o.FundingSourceToken) {
		return nil, false
	}
	return o.FundingSourceToken, true
}

// HasFundingSourceToken returns a boolean if a field has been set.
func (o *AutoReloadModel) HasFundingSourceToken() bool {
	if o != nil && !IsNil(o.FundingSourceToken) {
		return true
	}

	return false
}

// SetFundingSourceToken gets a reference to the given string and assigns it to the FundingSourceToken field.
func (o *AutoReloadModel) SetFundingSourceToken(v string) {
	o.FundingSourceToken = &v
}

// GetOrderScope returns the OrderScope field value
func (o *AutoReloadModel) GetOrderScope() OrderScope {
	if o == nil {
		var ret OrderScope
		return ret
	}

	return o.OrderScope
}

// GetOrderScopeOk returns a tuple with the OrderScope field value
// and a boolean to check if the value has been set.
func (o *AutoReloadModel) GetOrderScopeOk() (*OrderScope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderScope, true
}

// SetOrderScope sets field value
func (o *AutoReloadModel) SetOrderScope(v OrderScope) {
	o.OrderScope = v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *AutoReloadModel) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutoReloadModel) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *AutoReloadModel) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *AutoReloadModel) SetToken(v string) {
	o.Token = &v
}

func (o AutoReloadModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoReloadModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Association) {
		toSerialize["association"] = o.Association
	}
	toSerialize["currency_code"] = o.CurrencyCode
	if !IsNil(o.FundingSourceAddressToken) {
		toSerialize["funding_source_address_token"] = o.FundingSourceAddressToken
	}
	if !IsNil(o.FundingSourceToken) {
		toSerialize["funding_source_token"] = o.FundingSourceToken
	}
	toSerialize["order_scope"] = o.OrderScope
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

func (o *AutoReloadModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"currency_code",
		"order_scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutoReloadModel := _AutoReloadModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAutoReloadModel)

	if err != nil {
		return err
	}

	*o = AutoReloadModel(varAutoReloadModel)

	return err
}

type NullableAutoReloadModel struct {
	value *AutoReloadModel
	isSet bool
}

func (v NullableAutoReloadModel) Get() *AutoReloadModel {
	return v.value
}

func (v *NullableAutoReloadModel) Set(val *AutoReloadModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoReloadModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoReloadModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoReloadModel(val *AutoReloadModel) *NullableAutoReloadModel {
	return &NullableAutoReloadModel{value: val, isSet: true}
}

func (v NullableAutoReloadModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoReloadModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


