/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// PolicyRewardRuleType Type of reward rule.
type PolicyRewardRuleType string

// List of PolicyRewardRuleType
const (
	POLICYREWARDRULETYPE_CASHBACK PolicyRewardRuleType = "CASHBACK"
)

// All allowed values of PolicyRewardRuleType enum
var AllowedPolicyRewardRuleTypeEnumValues = []PolicyRewardRuleType{
	"CASHBACK",
}

func (v *PolicyRewardRuleType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PolicyRewardRuleType(value)
	for _, existing := range AllowedPolicyRewardRuleTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PolicyRewardRuleType", value)
}

// NewPolicyRewardRuleTypeFromValue returns a pointer to a valid PolicyRewardRuleType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPolicyRewardRuleTypeFromValue(v string) (*PolicyRewardRuleType, error) {
	ev := PolicyRewardRuleType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PolicyRewardRuleType: valid values are %v", v, AllowedPolicyRewardRuleTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PolicyRewardRuleType) IsValid() bool {
	for _, existing := range AllowedPolicyRewardRuleTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PolicyRewardRuleType value
func (v PolicyRewardRuleType) Ptr() *PolicyRewardRuleType {
	return &v
}

type NullablePolicyRewardRuleType struct {
	value *PolicyRewardRuleType
	isSet bool
}

func (v NullablePolicyRewardRuleType) Get() *PolicyRewardRuleType {
	return v.value
}

func (v *NullablePolicyRewardRuleType) Set(val *PolicyRewardRuleType) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyRewardRuleType) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyRewardRuleType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyRewardRuleType(val *PolicyRewardRuleType) *NullablePolicyRewardRuleType {
	return &NullablePolicyRewardRuleType{value: val, isSet: true}
}

func (v NullablePolicyRewardRuleType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyRewardRuleType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

