/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// RefundStatus Current status of the refund.
type RefundStatus string

// List of RefundStatus
const (
	REFUNDSTATUS_COMPLETED RefundStatus = "COMPLETED"
)

// All allowed values of RefundStatus enum
var AllowedRefundStatusEnumValues = []RefundStatus{
	"COMPLETED",
}

func (v *RefundStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RefundStatus(value)
	for _, existing := range AllowedRefundStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RefundStatus", value)
}

// NewRefundStatusFromValue returns a pointer to a valid RefundStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRefundStatusFromValue(v string) (*RefundStatus, error) {
	ev := RefundStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RefundStatus: valid values are %v", v, AllowedRefundStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RefundStatus) IsValid() bool {
	for _, existing := range AllowedRefundStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RefundStatus value
func (v RefundStatus) Ptr() *RefundStatus {
	return &v
}

type NullableRefundStatus struct {
	value *RefundStatus
	isSet bool
}

func (v NullableRefundStatus) Get() *RefundStatus {
	return v.value
}

func (v *NullableRefundStatus) Set(val *RefundStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableRefundStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableRefundStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefundStatus(val *RefundStatus) *NullableRefundStatus {
	return &NullableRefundStatus{value: val, isSet: true}
}

func (v NullableRefundStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefundStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

