/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.19
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DigitalWalletSamsungPayProvisionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DigitalWalletSamsungPayProvisionResponse{}

// DigitalWalletSamsungPayProvisionResponse struct for DigitalWalletSamsungPayProvisionResponse
type DigitalWalletSamsungPayProvisionResponse struct {
	// Unique identifier of the card resource to use for the provisioning request.
	CardToken string `json:"card_token"`
	// Date and time when the digital wallet provisioning request was created, in UTC.
	CreatedTime time.Time `json:"created_time"`
	// Date and time when the digital wallet token provisioning request was last updated, in UTC.
	LastModifiedTime time.Time `json:"last_modified_time"`
	PushTokenizeRequestData SamsungPushTokenizeRequestData `json:"push_tokenize_request_data"`
}

type _DigitalWalletSamsungPayProvisionResponse DigitalWalletSamsungPayProvisionResponse

// NewDigitalWalletSamsungPayProvisionResponse instantiates a new DigitalWalletSamsungPayProvisionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDigitalWalletSamsungPayProvisionResponse(cardToken string, createdTime time.Time, lastModifiedTime time.Time, pushTokenizeRequestData SamsungPushTokenizeRequestData) *DigitalWalletSamsungPayProvisionResponse {
	this := DigitalWalletSamsungPayProvisionResponse{}
	this.CardToken = cardToken
	this.CreatedTime = createdTime
	this.LastModifiedTime = lastModifiedTime
	this.PushTokenizeRequestData = pushTokenizeRequestData
	return &this
}

// NewDigitalWalletSamsungPayProvisionResponseWithDefaults instantiates a new DigitalWalletSamsungPayProvisionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDigitalWalletSamsungPayProvisionResponseWithDefaults() *DigitalWalletSamsungPayProvisionResponse {
	this := DigitalWalletSamsungPayProvisionResponse{}
	return &this
}

// GetCardToken returns the CardToken field value
func (o *DigitalWalletSamsungPayProvisionResponse) GetCardToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardToken
}

// GetCardTokenOk returns a tuple with the CardToken field value
// and a boolean to check if the value has been set.
func (o *DigitalWalletSamsungPayProvisionResponse) GetCardTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardToken, true
}

// SetCardToken sets field value
func (o *DigitalWalletSamsungPayProvisionResponse) SetCardToken(v string) {
	o.CardToken = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *DigitalWalletSamsungPayProvisionResponse) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *DigitalWalletSamsungPayProvisionResponse) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *DigitalWalletSamsungPayProvisionResponse) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetLastModifiedTime returns the LastModifiedTime field value
func (o *DigitalWalletSamsungPayProvisionResponse) GetLastModifiedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastModifiedTime
}

// GetLastModifiedTimeOk returns a tuple with the LastModifiedTime field value
// and a boolean to check if the value has been set.
func (o *DigitalWalletSamsungPayProvisionResponse) GetLastModifiedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModifiedTime, true
}

// SetLastModifiedTime sets field value
func (o *DigitalWalletSamsungPayProvisionResponse) SetLastModifiedTime(v time.Time) {
	o.LastModifiedTime = v
}

// GetPushTokenizeRequestData returns the PushTokenizeRequestData field value
func (o *DigitalWalletSamsungPayProvisionResponse) GetPushTokenizeRequestData() SamsungPushTokenizeRequestData {
	if o == nil {
		var ret SamsungPushTokenizeRequestData
		return ret
	}

	return o.PushTokenizeRequestData
}

// GetPushTokenizeRequestDataOk returns a tuple with the PushTokenizeRequestData field value
// and a boolean to check if the value has been set.
func (o *DigitalWalletSamsungPayProvisionResponse) GetPushTokenizeRequestDataOk() (*SamsungPushTokenizeRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PushTokenizeRequestData, true
}

// SetPushTokenizeRequestData sets field value
func (o *DigitalWalletSamsungPayProvisionResponse) SetPushTokenizeRequestData(v SamsungPushTokenizeRequestData) {
	o.PushTokenizeRequestData = v
}

func (o DigitalWalletSamsungPayProvisionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DigitalWalletSamsungPayProvisionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["card_token"] = o.CardToken
	toSerialize["created_time"] = o.CreatedTime
	toSerialize["last_modified_time"] = o.LastModifiedTime
	toSerialize["push_tokenize_request_data"] = o.PushTokenizeRequestData
	return toSerialize, nil
}

func (o *DigitalWalletSamsungPayProvisionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"card_token",
		"created_time",
		"last_modified_time",
		"push_tokenize_request_data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDigitalWalletSamsungPayProvisionResponse := _DigitalWalletSamsungPayProvisionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDigitalWalletSamsungPayProvisionResponse)

	if err != nil {
		return err
	}

	*o = DigitalWalletSamsungPayProvisionResponse(varDigitalWalletSamsungPayProvisionResponse)

	return err
}

type NullableDigitalWalletSamsungPayProvisionResponse struct {
	value *DigitalWalletSamsungPayProvisionResponse
	isSet bool
}

func (v NullableDigitalWalletSamsungPayProvisionResponse) Get() *DigitalWalletSamsungPayProvisionResponse {
	return v.value
}

func (v *NullableDigitalWalletSamsungPayProvisionResponse) Set(val *DigitalWalletSamsungPayProvisionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDigitalWalletSamsungPayProvisionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDigitalWalletSamsungPayProvisionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDigitalWalletSamsungPayProvisionResponse(val *DigitalWalletSamsungPayProvisionResponse) *NullableDigitalWalletSamsungPayProvisionResponse {
	return &NullableDigitalWalletSamsungPayProvisionResponse{value: val, isSet: true}
}

func (v NullableDigitalWalletSamsungPayProvisionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDigitalWalletSamsungPayProvisionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


